# Generated by Django 5.0.6 on 2024-05-16 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='siswa',
            table='siswa',
        ),
    ]
