# Generated by Django 5.0.6 on 2024-05-16 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sekolah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=100)),
                ('Poin', models.IntegerField()),
                ('Pesan', models.CharField(max_length=100)),
                ('Catatan', models.CharField(blank=True, max_length=200, null=True)),
                ('SekolahId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sekolah', to='sekolah.sekolah')),
            ],
        ),
    ]
