# Generated by Django 5.0.6 on 2024-05-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kategori_pelanggaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kategori',
            table='kategori_pelanggaran',
        ),
    ]
