# Generated by Django 5.0.6 on 2024-05-16 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0002_alter_kelas_table'),
        ('sekolah', '0003_sekolah_provinsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='Catatan',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='Nama',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='SekolahId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah'),
        ),
    ]
