# Generated by Django 5.0.6 on 2024-05-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0002_alter_sekolah_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='sekolah',
            name='Provinsi',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
