# Generated by Django 5.0.6 on 2024-05-16 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kategori_pelanggaran', '0001_initial'),
        ('petugas', '0001_initial'),
        ('sekolah', '0001_initial'),
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggarann',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TglJam', models.DateTimeField()),
                ('Poin', models.IntegerField()),
                ('Catatan', models.CharField(blank=True, max_length=200, null=True)),
                ('KategoriId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kategori_pelanggaran.kategori')),
                ('PetugasId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petugas.petugas')),
                ('SekolahId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah')),
                ('SiswaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa')),
            ],
        ),
    ]
